server:
  port: ${SERVER_PORT:8080}

external-apis:
  monitoring-base-url: ${BASE_URL}


spring:

  jpa:
    open-in-view: false

  application.name: device-management

  profiles:
    active: ${APP_PROFILE:dev}
